/********************************************************************************************************************
 * ******************************************************************************************************************
 * ******************************************************************************************************************
 *
 *                          AUTOGENERATED CODE : DO NOT EDIT
 *
 *
 * ******************************************************************************************************************
 * ******************************************************************************************************************
 ******************************************************************************************************************/

import { ApiProperty } from "@nestjs/swagger";
import {
    IsNotEmpty,
    IsDate,
    IsOptional,
    IsBoolean,
    IsString
} from "class-validator";

import { User } from "./User";
export class Book {
    @ApiProperty()
    @IsNotEmpty()
    @IsDate()
    createdAt: Date;
    @ApiProperty()
    @IsNotEmpty()
    id: number;
    @ApiProperty()
    @IsOptional()
    @IsBoolean()
    isPrimary?: boolean;
    @ApiProperty()
    @IsNotEmpty()
    @IsString()
    name: string;
    @ApiProperty()
    @IsOptional()
    owner?: User;
    @ApiProperty()
    @IsOptional()
    @IsString()
    ownerId?: string;
    @ApiProperty()
    @IsNotEmpty()
    @IsString()
    primaryCurrencyCode: string;
    @ApiProperty()
    @IsNotEmpty()
    @IsDate()
    updatedAt: Date;
}
