/********************************************************************************************************************
 * ******************************************************************************************************************
 * ******************************************************************************************************************
 *
 *                          AUTOGENERATED CODE : DO NOT EDIT
 *
 *
 * ******************************************************************************************************************
 * ******************************************************************************************************************
 ******************************************************************************************************************/

import { Injectable } from "@nestjs/common";
import { Prisma, User } from "@prisma/client";
import { PrismaService } from "nestjs-prisma";

@Injectable()
export class UserServiceBase {
    constructor(private prisma: PrismaService) {}

    async create(
        args: Prisma.UserCreateArgs
    ): Promise<Prisma.Prisma__UserClient<User | null>> {
        return await this.prisma.user.create(args);
    }

    async findAll(
        args: Prisma.UserFindManyArgs
    ): Promise<Prisma.Prisma__UserClient<User[] | null>> {
        return await this.prisma.user.findMany(args);
    }

    async findOne(
        args: Prisma.UserFindUniqueArgs
    ): Promise<Prisma.Prisma__UserClient<User | null>> {
        return await this.prisma.user.findUnique(args);
    }

    async update(
        args: Prisma.UserUpdateArgs
    ): Promise<Prisma.Prisma__UserClient<User | null>> {
        return await this.prisma.user.update(args);
    }

    async remove(
        args: Prisma.UserDeleteArgs
    ): Promise<Prisma.Prisma__UserClient<User | null>> {
        return await this.prisma.user.delete(args);
    }
}
